var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                                 xx!xx          ",
   "                                                                 x!!!x          ",
   "                                                                 xx!xx          ",
   "                                                                  xvx           ",
   "                                                                            xx  ",
   "                                          o o                                x  ",
   "                        o                                                    x  ",
   "        *                                                                  o x  ",
   "                        o                                                    x  ",
   "     @                                                                       x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xx!!!!!!!!!!!!!!!!!!xxx!!!!!!!!xxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx  ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
   
   
  ["               vvvvvvvvvvvvvvvvvvvvvv                 vvvvvvvvvvvvvvvvvvvvvvvvvv                                  ",
   "                                      																			  ",
   "                                        																		  ",
   "                                     																			  ",
   "                                      																			  ",
   "                                       																		      ",
   "                                       																			  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                              o                   ",
   "                                               x     x                           xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                  o            x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                  o            x     x      o  o     x   x         x         x                    ",
   "                                x   x          x     x               x   x         x         x                    ",
   "     T                          x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "                                x o x          x    xx               x   x   x               x                    ",
   "     @                          x   x          x     x               x   x   x               x                    ",
   "    xxx                         x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x                        xx o xx         x     x               x!!!!!!!!!!!x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x!!!!!!!!!!!x x         x                    ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!!xx !                    xx     xx                     ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx  !                     xxxxxxx                      ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
   
   
  ["    vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv   ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x                                                                                                        x  ",
   "  x      @                                  oooooooooooooooooo                                             x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
 
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
